import DS from 'ember-data';

export default DS.Model.extend({
  		
	nombre: DS.attr("string"),
	rfc: DS.attr("string"),
	curp: DS.attr("string"),
	afiliacion: DS.attr("string"),
	telefonocasa: DS.attr("string"),
	telefonotrabajo: DS.attr("string"),
	fechanacimiento: DS.attr("string"),
	lugarnacimiento: DS.attr("string"),
	nacionalidad: DS.attr("string"),
	estadocivil: DS.attr("string"),
	situacion: DS.attr("string"),
	regimen: DS.attr("string"),
	ocupacion: DS.attr("string"),
	domicilio: DS.attr("string"),
	colonia: DS.attr("string"),
	ciudad: DS.attr("string"),
	estado: DS.attr("string"),
	codigopostal: DS.attr("string"),
	email: DS.attr("string"),
	tipoTramite: DS.attr("string"),
	titularIfe: DS.attr("boolean"),
	titularCopiasIfe: DS.attr("boolean"),
	titularCartaEmpresa: DS.attr("boolean"),
	titularCopiaAfore: DS.attr("boolean"),
	titularActaNacimiento: DS.attr("boolean"),
	titularCopiasActaNacimiento: DS.attr("boolean"),
	conyugerfc: DS.attr("string"),
	conyugenombre: DS.attr("string"),
	conyugecurp: DS.attr("string"),
	conyugefechanacimiento: DS.attr("string"),
	conyugelugarnacimiento: DS.attr("string"),
	conyugenacionalidad : DS.attr("string"),
	conyugeocupacion: DS.attr("string"),
	conyugeIfe: DS.attr("boolean"),
	conyugeCopiasIfe: DS.attr("boolean"),
	conyugeCartaEmpresa: DS.attr("boolean"),
	conyugeCopiaAfore: DS.attr("boolean"),
	conyugeActaNacimiento: DS.attr("boolean"),
	conyugeCopiasActaNacimiento: DS.attr("boolean"),
	actaMatrimonio: DS.attr("boolean"),
	copiasActaMatrimonio: DS.attr("boolean")

});
